highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins:
  - jekyll-sitemap
permalink: blogs/:title/
title: Shobhit Porwal
email: shobhit.porwal94@gmail.com
description: Website of Shobhit Porwal, Data Science Enthusiast
keywords: shobhit, porwal, gurgaon, security, developer, geek, programmer, github
baseurl: ""
url: https://shobhitporwal.com
name: Shobhit Porwal\'s blog
author:
  name: Shobhit Porwal
  email: shobhit.porwal94@gmail.com
