github_url: https://github.com/s-porwal
linkedin_url: https://in.linkedin.com/in/s-porwal
about_url: /about/
archive_url: /archive/
projects_url: /projects/
contact_url: /contact/
disclaimer_url: /disclaimer/
resume_url: /resume.pdf
rss_url: /atom.xml
sitemap_url: /sitemap.xml